#!/usr/bin/with-contenv bash

s6-echo "Starting Unbound"
source /etc/default/unbound
/usr/lib/unbound/package-helper chroot_setup
/usr/lib/unbound/package-helper root_trust_anchor_update
/usr/sbin/unbound -d -p $DAEMON_OPTS

